#! /bin/sh

xsetroot -cursor_name left_ptr &

xrandr \
	--output HDMI-1 --primary --mode 1920x1080 --rotate normal \
	--output DVI-D-1 --mode 1920x1080 --rotate normal --right-of HDMI-1 \
	--output VGA-2 --off --output VGA-1-1 --mode 1366x768 --rotate normal --left-of HDMI-1

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor VGA-1-1 -d I II III IV
bspc monitor HDMI-1 -d V VI
bspc monitor DVI-D-1 -d VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Autostart
picom &
feh \
	--recursive --bg-scale --randomize /usr/share/backgrounds/archlinux \
	--recursive --bg-scale --randomize /usr/share/backgrounds/archlinux \
	--recursive --bg-scale --randomize /usr/share/backgrounds/archlinux
$HOME/.config/polybar/launch.sh
