#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor VGA-1-1 -d 1 2 3
bspc monitor HDMI-1 -d 4 5 6
bspc monitor DVI-D-1 -d 7 8 9

bspc config border_width        2
bspc config window_gap          8 
bspc config top_padding		0
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefoxdeveloperedition desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
